server:
  port: 8080
  tomcat.uri-encoding: UTF-8
  compression:
    enabled: true
  connection-timeout: 1000s

spring:
  application:
    name: myclient
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mmsdb?&useUnicode=true&characterEncoding=utf8
      username: hjj
      password: hjj
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  messages:
    encoding: utf-8
  output:
    ansi:
      enabled: detect
  thymeleaf:
    cache: false
    check-template: true
    enabled: true
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    encoding: utf-8
  resources:
    add-mappings: true
  servlet:
    multipart:
      max-file-size: 1024Mb
      max-request-size: 2048Mb

logging:
  path: /home/junf/IdeaProjects/one/src/
  level:
     org.springframework.web: INFO
     com.junf.drhat: DEBUG
     org.springframework.security: INFO
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml






